### ISSUE TITLE
PokemonList could be a Hashmap, for more efficient lookup

### ISSUE THREAD

**Issue by dennism1997** [Ishadijcks/pokeclicker#1]

**Comment by Aegyo** [comment]
Is a Hashmap any faster than keeping it as an array and just doing PokemonList[id]? I'm not sure there is any time when you wouldn't have the id available to use.

**Comment by dennism1997** [comment]
It is when you are are getting the pokemon by name, which is kinda preferred since it improves readability

**Comment by dennism1997** [comment]
closed by #10
