### ISSUE TITLE
Make a help tab?

### ISSUE THREAD

**Issue by tklaxbro** [Ishadijcks/pokeclicker#103]
<h6>Heyo, sorry for the two week inactivity, cousin got married and never informed you all.</h6>

<h3>I suppose we make a help tab to clearly explain some of the things that need to be explained.</h3>
Inside the help tab we can have a navigation bar with each of the things needing help with, a shards tab, underground tab, whatever.

**Comment by Ishadijcks** [comment]
Do you think that's better than have a little questionmark at each feature that explains it?

If so, why?

**Comment by tklaxbro** [comment]
I guess the question-mark would be better, they wouldn't have to go back to the help tab if help was needed. But then there is the issue of getting help with timed things like dungeons, how to maneuver around and things of that sort.

**Comment by Ishadijcks** [comment]
Worked out in better detail here #5
