### ISSUE TITLE
Support multiple regions

### ISSUE THREAD

**Issue by dennism1997** [Ishadijcks/pokeclicker#111]
- [ ] Create a johto svg map
- [ ] Decide when it is possible to go to a new region
- [ ] Adapt code so that multiple regions is possible (not that much work i think)

**Comment by Aegyo** [comment]
Same as #165

**Comment by xpvolcanionYT** [comment]
I can supply the region maps and make the region maps look like that Kanto map. The only problem are the codes. We have to make a folder where all the .js scripts go.
