### ISSUE TITLE
include html inside html

### ISSUE THREAD

**Issue by dennism1997** [Ishadijcks/pokeclicker#112]
Right now, all html is inside the same file, which leads to a big mess.

What would be better, is some sort of include system, where you can include html files inside other html files. 
Me and @Ishadijcks don't know anything about this though. Does anybody have an idea?

**Comment by tklaxbro** [comment]
just `href` them?

ex: have the main be something like `pokeclicker.com/main.html` and have a button to the underground like 
`<a href="pokeclicker.com/underground.html">Underground</a>`

or do you mean reference other html files without having to load the page again?

**Comment by dennism1997** [comment]
Yeah the second thing. We would just like a way to keep everything the same as it is, while having a better structure

**Comment by dennism1997** [comment]
I think I got it working with [this](https://www.html5rocks.com/en/tutorials/webcomponents/imports/)
Tried it with the start sequence modal and it worked seamlessly

**Comment by dennism1997** [comment]
Okay I got it working with the gymView too like this:

Declare the link before jquery etc. Just on top of the html:
![image](https://user-images.githubusercontent.com/8763360/29187531-5f1c3eb0-7e10-11e7-9c6b-4c3784fdf0db.png)

Create a html file, and cut/paste all the code you want included, and wrap it inside a template element:
![image](https://user-images.githubusercontent.com/8763360/29187600-a4ad2a3e-7e10-11e7-8536-5da934613895.png)

Then include the file inside the html. This can be done once for each file, or we can put all the includes inside one script element. I think per element is more clear and also easier, since you keep the order of the elements correct automatically.
![image](https://user-images.githubusercontent.com/8763360/29187502-43c87dfe-7e10-11e7-878c-1a15d2358b80.png)

A few notes:
- It needs to be inside a `<template>`, as to make sure javascript and stuff loads on include and not on import
- Gulp compiles all html files inside the script folder, and puts them inside the html folder, keeping the same subfolders (so `gymView.html` is stored inside html/gym/)

What do you guys think? @tklaxbro @Aegyo @Ishadijcks

**Comment by BaineGames** [comment]
With the gulp-import-html solution I have implemented in pull request, i beleive this is taken care of. @dennism1997
