### ISSUE TITLE
Old save converter to keep shinies

### ISSUE THREAD

**Issue by dennism1997** [Ishadijcks/pokeclicker#116]
The converting part should be easy: Just take in the save file (which is a base64 encoded JSON file) and convert it.

I'm not really sure how we wanna make the shinies appear for the players. I have thought of several options. For example, if you had a shiny squirtle:

1. You keep seeing shiny squirtles until you catch one
2. You get the squirtle at the start of the game (or after you get your first starter or something)
3. There is a pokemon lab somewhere on the map where you can receive your shinies (or convert them?)

Let me know what you guys think!

**Comment by Aegyo** [comment]
What was the plan for getting shinies from your previous prestige?

**Comment by dennism1997** [comment]
Not sure, but I think those two can be the same

**Comment by Aegyo** [comment]
I prefer the idea of having to catch the pokemon first, and then have that converted into the shiny version somehow (either automatically or via the pokemon lab location you mentioned)

**Comment by Ishadijcks** [comment]
The idea was that the shiny property of a Pokémon is saved. So if you don't have the Pokémon, you don't have it shiny either. Once you capture any version of that Pokémon, it is displayed as a shiny version.
