### ISSUE TITLE
Dungeon map overlay

### ISSUE THREAD

**Issue by dennism1997** [Ishadijcks/pokeclicker#118]
Dungeon maps look pretty basic right now, maybe we can make some overlay where there is a background behind the dungeon, which depends on the type of dungeon (forest, cave, etc.) or even make one specific per dungeon.

**Comment by Aegyo** [comment]
We could probably have relevant images for the dungeon rooms instead of just colours

**Comment by Ishadijcks** [comment]
Not entirely sure what you mean, could you make a mockup image?

**Comment by Ishadijcks** [comment]
Not a priority, closed for now
