### ISSUE TITLE
Start menu should be a drawer layout

### ISSUE THREAD

**Issue by dennism1997** [Ishadijcks/pokeclicker#12]
Something like this:
http://git.blivesta.com/drawer/

**Comment by dennism1997** [comment]
Is this in progress?

**Comment by Ishadijcks** [comment]
You kinda started with the top right menu right?

**Comment by dennism1997** [comment]
Kinda, but was not planning on working on it further for the time being

**Comment by Ishadijcks** [comment]
I see, I'll remove the label
