### ISSUE TITLE
implement evolution stones

### ISSUE THREAD

**Issue by dennism1997** [Ishadijcks/pokeclicker#133]
The evolution stones need to be implemented.

- [x] When you activate an evo stone, a dialog should come up that shows all pokemon that can be evolved through that stone (don't forget eevee's)
- [x] There needs to be an amount button, where you can select how many stones you want to use at the same time
- [x] There should be an "until shiny" button, that lets you keep evolving pokemon until one of them turns shiny

**Comment by Nyargleblargle** [comment]
In 0.9, even in the endgame, I never had many stones at a time. Is multi-use really needed?

**Comment by Ishadijcks** [comment]
Yeah, for endgame shiny hunters
