### ISSUE TITLE
Trainer battles

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/pokeclicker#138]
When the player has the "VS seeker" Key item:

After a random amount of time, depending on where the player is on the map, he can get a call from a trainer who wants to challenge him. When accepted the battle works similar to a gym battle.

Rewards could be items, quest points, money and such. Depends on the type of trainer.

Random trainers would include the rival at certain story points.

There would be a grid that displays which trainers you've encountered similar to the Fame Checker

**Comment by xpvolcanionYT** [comment]
It would be a great addition to the game to make it more fun.
