### ISSUE TITLE
Unlocked town and dungeons are the same colour as routes

### ISSUE THREAD

**Issue by Aegyo** [Ishadijcks/pokeclicker#159]
Everything ends up being the same colour, I think this looks far too plain compared to how it was before.

Dungeons and towns should have a different colour than routes to show when they are unlocked, preferably also different from each other. Might be a good idea to decide on an unlocked colour, and then make the locked version pretty much the same, but more grey.

**Comment by Ishadijcks** [comment]
Agreed

**Comment by Ishadijcks** [comment]
This is no longer the case?
