### ISSUE TITLE
How to create an observable number array with knockout?

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/pokeclicker#18]
`Player.routekills` needs to be observable so we can show how many kills the player has on this route.
Updating the value does not work however.

Things I tried:
```
private static _routeKills: KnockoutObservableArray<number> = ko.observableArray<number>();

public static initializeRouteKills(){

        let routeKill: KnockoutObservable<number> = ko.observable(0);
        Player.routeKills.push(routeKill);
    }
```

"TS2349: Cannot invoke an expression whose type lacks a call signature."

```
private static _routeKills: KnockoutObservable<number[]> = ko.observable(Array.apply(null, Array(GameConstants.AMOUNT_OF_ROUTES)).map(Number.prototype.valueOf, 0));

   public static addRouteKill(){
        Player.routeKills()[Player.route()]++
    }
```

This correctly adds a number to the list, but it doesn't update the observer for some reason.

Please help :(

**Comment by Aegyo** [comment]
Maybe I am misreading this, but it seems like the array is filled with just normal numbers, when you want it to be filled with Knockout Observables. Maybe changing the Array map to `.map( () => { return ko.observable(0); }`

**Comment by Ishadijcks** [comment]
Fixed by @Aegyo
