### ISSUE TITLE
Scale gym health

### ISSUE THREAD

**Issue by dennism1997** [Ishadijcks/pokeclicker#191]
The gym pokemon health are now some random numbers. Maybe we can scale them according to their difficulty. Then each pokemon after the first gets a portion of the first pokemon's health extra, so every pokemon is stronger than the previous one. 
For example, the first gym has a Geodude with 1000 health and then Onix has 1000 + (1/10 * 1000) = 1100 health.

**Comment by Ishadijcks** [comment]
I think manual numbers are easier to tweak, and you can create nicer looking numbers. Don't think this is worth the effort for the gain.
