### ISSUE TITLE
Dungeon Token Bug

### ISSUE THREAD

**Issue by xwerswoodx** [Ishadijcks/pokeclicker#201]
When we disable caught pokemons that we already caught, we can't earn dungeon points, so we stuck on route 3 because of this.

`        player.gainDungeonTokens(Math.floor(this.enemyPokemon().level / 2));`
This code is declared in public static catchPokemon() function. I don't know if this is your own choice, but if not just cut this code under this.gainItem(); inside public static defeatPokemon() function in Battle.ts file. (I know you can do this, I just tell you because I don't want you to lose your time with this.)

**Comment by Aegyo** [comment]
I think requiring players to catch pokemon they already have to earn dungeon tokens is a good idea, otherwise nobody would bother to use pokeballs on caught pokemon, and you would only need a few hundred pokeballs for the entire game.

**Comment by xwerswoodx** [comment]
I understand what you mean, but this change is only way to continue game after route 3. But if they fix quest issue, this is not problem. But on the other hand, maybe catching pokemon can increase attack (for example catching 10 charmander, can increase our charmander's attack by 1) so we can caught pokemons to increase out pokemons attack damage.

**Comment by Aegyo** [comment]
Breeding pokemon will increase it's attack a little each time, and there is currently no cap on the attack increase.

If you want to continue past route 3 with the game in it's current state, either cheat the dungeon ticket in, or give yourself enough quest points to buy it. This won't be an issue when the game is released though.
