### ISSUE TITLE
Shop Multiplier Glitch

### ISSUE THREAD

**Issue by xwerswoodx** [Ishadijcks/pokeclicker#203]
It seems like there is a bug on shop multiplier. Because I bought 1500 pokeballs from shop and 1 pokeball price go from 100 to 7.90T
![asdasd](https://user-images.githubusercontent.com/6155640/33624116-352e6272-d9eb-11e7-877e-b92bef47588f.png)

After 1 hour afk pokemon killing, it nearly same (hitting one time to pokemon)
![asd](https://user-images.githubusercontent.com/6155640/33624115-35156470-d9eb-11e7-98a7-1dc8cf4e583e.png)

So if you don't change multiplier (or maybe remove it) it's not possible to buy pokeballs anymore.

**Comment by Aegyo** [comment]
This isn't a glitch, price increases exponentially when you buy, and decreases linearly as you defeat pokemon. You are supposed to just buy a few at a time.

Maybe there could be some info somewhere while you are buying which tells you what the cost will increase to after buying, but I'm pretty sure it will always be less than whatever you are paying (assuming you buy more than 1)

**Comment by xwerswoodx** [comment]
7.9T that we can see there, this could be more than 79T or 790T so it seems like impossible to buy pokeballs again. If I left game afk for a month I don't thing it comes to 100 again, it's not possible to come that much price with 1500 pokeballs from 100 to 7.9T, this could be possible if game calculate price with 1500 pokeballs base price (I mean starting with 150k$) not base value (which is 100$)

**Comment by Aegyo** [comment]
Cost increases by 2% for each item bought, so the price after 1500 pokeballs would be (100 * 1.02^(1500))

https://www.wolframalpha.com/input/?i=100+*+1.02%5E1500

7.948e14, or 794.8 trillion

Buying this many happens to cost about 50 times what the cost is raised to, so it would never be a huge issue anyway.

**Comment by xwerswoodx** [comment]
Hmm, it seems you are right, I haven't thought 100 could be that much :o sorry for my bad math lol, but except this, I am still think this increase still too high, we are talking about 794.8T. For quest we will need 400-500 pokeballs, so noone will buy 10 pokeballs ang wait a little and go again to shop to buy 10 pokeballs.

**Comment by Aegyo** [comment]
That's a fair point. Initial values for that were based on time taken to catch, I hadn't considered pokeball cost.

**Comment by Ishadijcks** [comment]
Agreed, I changed shop prices to decrease exponentially as well to avoid getting 'stuck' on an insane price
