### ISSUE TITLE
Pre-load images of pokémon so they don't flicker on first load

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/pokeclicker#21]
I looked into using sprites, but I'm not sure that's possible with Knockout.
Here is the code for loading the image:
```
<div data-bind="ifnot: Battle.catching">
    <img data-bind="attr:{ src: '/assets/images/pokemon/' + Battle.enemyPokemon().id() + '.png' }"/>
</div>

<div data-bind="if: Battle.catching">
    <img data-bind="attr:{ src: '/assets/images/pokeball.png' }"/>
</div>
```

Pretty happy with it, so I'd rather keep it how it is.
I tried this as a pre-loader, but it didn't work:

```
    let img = new Image();
    img.src = '/assets/images/pokeball.png';
    for(let i = 1; i<150; i++) {
        img.src = '/assets/images/pokemon/' + i + '.png';
    }
```

**Comment by Aegyo** [comment]
if you give the div which encloses the two image divs a height of about 96px, the health bar doesn't flicker around. This isn't exactly the solution you are looking for, but maybe better than forcing the player to load all pokemon images?

If an image doesn't load fast enough, there will just be a blank space until it has loaded.

I can make a pr with this change if you want.

**Comment by Ishadijcks** [comment]
Ha good idea!

**Comment by dennism1997** [comment]
Fixed in 2a755a8ed9baeb273379530efa1907ca50c2724f

**Comment by Aegyo** [comment]
I meant the div 1 layer higher (so it only needed to be applied to a single element), but if this works too then there is no problem ^_^

**Comment by Ishadijcks** [comment]
I am keeping this issue open, in case somebody comes along with a better solution.

**Comment by tklaxbro** [comment]
It seems like it can be shortened, I don't even know if this works, and it doesn't have any of the towns, leaders, or badges yet but here is my go...
`Images = [ "https://ishadijcks.github.io/background.png", "https://ishadijcks.github.io/favicon.ico", "https://ishadijcks.github.io/kanto.png", "https://ishadijcks.github.io/pokeball.png", "https://ishadijcks.github.io/pokeclickerlogo.png" ];

for (i = 0; i <= 150; i++) {
    pic = i;
}

images.push("https://ishadijcks.github.io/pokeclicker/src/assets/images/pokemon" + pic + ".png");
images.push("https://ishadijcks.github.io/pokeclicker/src/assets/images/shinypokemon" + pic + ".png");

function load_images()
{
    for(i=0; i<images.length; i++){
        var my_image = new Image();
        my_image.src = Images[i];
    }
}
load_images();`

**Comment by Ishadijcks** [comment]
I have tried this, but I think it doesn't actually load the images as they are not displayed somewhere on the page.
