### ISSUE TITLE
Tutorial quests

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/pokeclicker#224]
Important notes:
- [x] Never introduce multiple mechanics at the same time. So don't have the first quest be 'do something for the first time'.

- [x] Autocomplete quests during the tutorial, or make it mandatory to complete them before continuing.
This is so the player can't be behind on quests, getting stuck on one-time event quests that can no longer be completed (e.g. pick a starter quest after a started has already been picked.

- [x] Nerf the shopprice of the dungeon ticket to 250

Questlist
- [x] Deal 10 damage. 10 QP
- [x] Capture a new Pokémon. 20 QP
- [x] Kill 5 Pokémons on route 2. 30 QP
- [x] Defeat the Pewter City gym 1 time. 40 QP
- [x] Buy 50 PokéBalls. 50 QP
- [x] Kill 10 Pokémons on route 3. 100 QP

After this you have exactly the amount of a dungeon ticket, as you are about to be stuck on the dungeon after route 3

**Comment by BaineGames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [asdfazsdf](https://trello.com/c/mZfkcKvM/2-asdfazsdf)

**Comment by Aegyo** [comment]
> Deal 10 damage. 10 QP
We don't currently track total damage dealt, should I add it for this, or just change the quest to defeat 1 pokemon? Another option would be creating a click x times quest since I think we do track that for the achievements.

**Comment by Ishadijcks** [comment]
Not a fan of click quests, might turn people off. 1 defeat is better.
