### ISSUE TITLE
mega evolutions

### ISSUE THREAD

**Issue by xrago** [Ishadijcks/pokeclicker#237]
1.  need to add keystones to dungeons
2.  need to add sprites
3.  need to add mega evolution animation

**Comment by Ishadijcks** [comment]
What would they add as an interesting dynamic?

If it is simply increased damage I doubt it's worth the effort.

**Comment by xrago** [comment]
it could bring in more people to play though. think about that.

**Comment by DreadStruck** [comment]
I think that it would be a fascinating idea. Sure, it might only buff its attack at first, but I think you could implement a system where the longer you have a certain pokemon mega evolved, the more boosts / bonuses it unlocks. For instance, a Blastoise could at first just get buffed attack, but over time it could boost EXP / Money gain from water type pokemon, increase chance of finding shiny water types while mega evolved, or even allow you to unlock access to more keystones.

**Comment by DreadStruck** [comment]
Again, thats JUST Blastoise though, and implementing the gradual buff gains would be an absol-ite PAIN (If you get what I mean :3)

**Comment by xrago** [comment]
whatever you guys decide to do ill wait for johto still

**Comment by Ishadijcks** [comment]
Closing it for now
