### ISSUE TITLE
Rare Pokemon

### ISSUE THREAD

**Issue by DreadStruck** [Ishadijcks/pokeclicker#244]
Instead of an item made for finding shiny's, why not have an item that not only helps you locate shiny's BUT helps you find the rarer pokemon. For example, in route 1 you can find pidgey and rattata. With the item equipped, you can find pokemon like the starters AND shiny variants. Just an idea, but it would be a wonderful addition.

**Comment by DreadStruck** [comment]
BTW, I'm a huge fan of your work and, although I can't help with the coding, I'm a creative person and love helping others simply with ideas. If you ever need some more ideas, or maybe a math fanatic, notify me ;)

**Comment by Ishadijcks** [comment]
'Rare' Pokémon can be captured in the Safari Zone with the use of the right PokéBlocks created from berries :)

We do need some math done to calculate how long each part of the game takes. Email me if you're interested in that :)

**Comment by DreadStruck** [comment]
Sorry I couldn't get back sooner, I was dealing with my birthday and
family. Anyways, I'd be glad to help you with calculating certain things in
the game. I'm not the best out there, but I'm sure I'll be of use. :)

**Comment by DreadStruck** [comment]
I'd also be fine doing some artwork, as I'm equally as good with 2d art as
I am math.

**Comment by DreadStruck** [comment]
If you're interested in me being an artist as well, email me. I'd be happy
to help in any ways possible. To be honest, I was hoping that through my
help we can get the alpha release earlier than scheduled time. I want to
take up as many possible jobs I can in order to help. I'll be open any time
after 3:45 PM EST to work on my assigned tasks.
