### ISSUE TITLE
Money for multi-buy is not correct for pokeballs (might be intentional)

### ISSUE THREAD

**Issue by tklaxbro** [Ishadijcks/pokeclicker#249]
I realized that this might be an accident so I gave a warning in the title. 
the final lines for the price of an item is as follows: 
```js
if (this.name() == "Pokeball") {
    return this.price() * amount;
}
let res = (this.price() * (1 - Math.pow(GameConstants.ITEM_PRICE_MULTIPLIER, amount))) / (1 - GameConstants.ITEM_PRICE_MULTIPLIER);
return Math.floor(res);
```

I don't know why you'd want to have the pokeballs not follow this patern. 
Sidenote: They still increase in price after you buy, just the math isn't correct for bulk buys. -> 
1st pokeball is 100, second is 101. But 10 cost 1000 flat.

**Comment by Ishadijcks** [comment]
@dennism1997
