### ISSUE TITLE
Create a chat system

### ISSUE THREAD

**Issue by dennism1997** [Ishadijcks/pokeclicker#27]
We want the chat system to support:
Must have:
- [ ] Chat roles
- [ ] Login (something like passport-js)
- [ ] Ignore list
- [ ] pick username at sign-up

Should have:
- [ ] Emoticons
- [ ] Private messages
- [ ] Multiple Rooms

**Comment by elegant-rake** [comment]
A few comments:

Regarding a login system, Isha and I had previously discussed using OAuth for this. Specifically reddit OAuth or Guest accounts. This would allow a simple approach to Roles (Admin, Moderator, Etc) and require very little extra effort on our end (i.e. we wouldn't require adding a database just for chat logins/passwords).

Using OAuth could pretty drastically reduce the amount of logic and authentication we would actually have to do.

**Comment by Aegyo** [comment]
https://socket.io/ seems like a good choice for the actual chat system.

**Comment by Ishadijcks** [comment]
You sure? :p
![image](https://user-images.githubusercontent.com/9715314/27751906-ecbbbf04-5dde-11e7-9ea8-40eceb3175e5.png)

**Comment by dennism1997** [comment]
Passport uses OAuth too if I recall correctly. And then you can use facebook/google/twitter/reddit/github to authenticate

**Comment by Aegyo** [comment]
Is that 502 from trying to access socket.io? The page loads fine for me.

**Comment by Ishadijcks** [comment]
Haha yeah it does for me after refreshing, just thought it was funny.

**Comment by elegant-rake** [comment]
Socket.io is what I will be using, yeah. I wasn't aware of passport, I had been implementing the OAuth from scratch mostly as a learning experience, but I'll take a look. Thanks

**Comment by Ishadijcks** [comment]
Any idea when you can get a prototype working? No hurry :)

**Comment by Ishadijcks** [comment]
@elegant-rake update?

**Comment by BaineGames** [comment]
The requirements for this should be reviewed and updated. @Ishadijcks said no private messages for example. Also you can move this to review in the board as the PR for chat system v1 is in place.

**Comment by Swaga1icous** [comment]
What about discord?  I know a lot of people like to use discord as a way to chat.  With discord, you can send out messages to everyone in the server at once, and you can see past messages so you don't have to be on the message board at all times.  IIRC, you can also set up roles, privileges, and even discord bots for perhaps in-game bonus?

**Comment by DreadStruck** [comment]
I'd say discord is perfect. I already use it myself, so I could easily
start up a new server and transfer ownership and the proper roles to
everyone else.

**Comment by Ishadijcks** [comment]
Discord could be useful, except it is less practical for the casual gamer. Not everyone wants to use it and having an in-game chat would provide a better experience. The question is if it is worth the development time and effort.

**Comment by DreadStruck** [comment]
I'm not sure it is, you'd have to make an entirely new chat system AND take the time to find somewhere to put it, as well as making sure it doesn't interfere with other aspects of the game. It's just too much work for an "alternative" to discord.

**Comment by BaineGames** [comment]
@Ishadijcks can we kill this since we have a discord now :)

**Comment by Ishadijcks** [comment]
Yep :)
