### ISSUE TITLE
Shop Eggs Price

### ISSUE THREAD

**Issue by Aegyo** [Ishadijcks/pokeclicker#281]
The currency for shop eggs is currently money, previous version of pokeclicker required quest points.

This is defined in the constructor for EggItem, fourth parameter of the super call needs to specify quest points.

Also, they all cost 1000 right now. We don't seem to have any consistency in setting the price for items: Pokeball prices are defined in GameConstants, but the price for KeyItems is passed into the constructor. Everything else is just a default hardcoded in it's constructor.

Not sure if we want to figure out some balancing for these prices first, or just use the old values, but whenever we do this it might be a good idea to have a consistent method of controlling base prices across all item types.

**Comment by fuws** [comment]
We can have them all be defined in `GameConstants` and then pass those into the constructors. This is so you at least don't have to hunt code down when balancing them. Maybe a better solution exists but at least this one works for now.

**Comment by Ishadijcks** [comment]
Agree @fuws. Having them all as global constants and then passing them to the constructor makes sense.

**Comment by fuws** [comment]
#303 only deals with moving item price code into `GameConstants`. We should make the price changes into separate issues.
