### ISSUE TITLE
Lose starter pokemon, Missing UI

### ISSUE THREAD

**Issue by RedSparr0w** [Ishadijcks/pokeclicker#286]
## Description
If you refresh the page after initial load, You do not get a chance to catch the starter pokemon, And Half of the UI doesn't appear.

If you select a starter, the UI will appear, But you will not be able to battle that starter pokemon

## Expected Behavior
Should be able to catch the starter pokemon
UI should appear

## Current Behavior
Do not get the chance to catch the starter pokemon
Missing UI

## Steps to Reproduce

1. Load page (New Save)
2. Do/Don't Select a starter (do not battle)
3. Wait a little bit for the game to auto save
4. Refresh the page
5. Will be battling a Rattata or Pidgey

## Screenshot of screen or console (optional)
This is what you see if you don't select a starter at all
![image](https://user-images.githubusercontent.com/7288322/58289209-e5664100-7e09-11e9-9dbf-5b104ca2f485.png)

**Comment by Ishadijcks** [comment]
Multiple ways to solve this:

- Don't save when the user doesn't have a starter.
- On load, if the user doesn't have a starter, run the StartSequence again.

I think the second solution would be the cleanest, but @dennism1997 might know best.

**Comment by RedSparr0w** [comment]
I agree the 2nd option seems like it would work best.

On a side note, is the starter pokemon shiny locked, or is there a possibility to start with a shiny?

**Comment by Ishadijcks** [comment]
It actually is possible, however unlikely

https://github.com/Ishadijcks/pokeclicker/blob/develop/src/scripts/StartSequenceRunner.ts#L9
