### ISSUE TITLE
Shop item selection should include currency

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/pokeclicker#308]
Currently:

![image](https://user-images.githubusercontent.com/9715314/58585517-3ab2b000-8259-11e9-91fa-c90c2cb56107.png)

Expected:
![image](https://user-images.githubusercontent.com/9715314/58585745-ccbab880-8259-11e9-854c-653a51f2acb8.png)

**Comment by fuws** [comment]
The `develop` branch seems fine. #305 introduced this bug.

**Comment by RedSparr0w** [comment]
Nice catch!, looks fine for me too on the `develop` branch

**Comment by Ishadijcks** [comment]
Fixed
