### ISSUE TITLE
Evolution stone interface

### ISSUE THREAD

**Issue by fuws** [Ishadijcks/pokeclicker#317]
**Two things:**

1. **Issue:** No matter which amount the player selects, the stones usage always stops when a shiny is encountered. This mechanic is great. But this isn't very clear to the player. E.g. player may think the 1000 option would keep using the stone even if shiny is encountered.
![image](https://user-images.githubusercontent.com/36806183/58676156-2dfb8e00-8325-11e9-915f-8957d6e6e115.png)

**Suggested improvement**: Make it clear to the player that stone usage always stops after a shiny is encountered. Change the `Until shiny` to `Infinity` or the infinity symbol.

2. **Issue:** When a shiny is encountered, there is an off-by-one error when displaying how many stones got used. 
![image](https://user-images.githubusercontent.com/36806183/58676382-1e307980-8326-11e9-994e-f9f8860fca02.png)

**Console code to reproduce:**
`player.gainItem("Fire_stone", 1000) // Or any other stone`
`GameConstants.SHINY_CHANCE_STONE = 1`
Then use the stone on a Pokemon to evolve.

**Comment by pockeclicker** [comment]
silvouplait si ya encore quelqun aide moi svp je galere a konto je peux pas utiliser mes pierres sur kadabra machopeur jai trop envie daller a joto svp aide moi
