### ISSUE TITLE
Repeated breeding crashes chrome 

### ISSUE THREAD

**Issue by Quindon** [Ishadijcks/pokeclicker#332]
Repeated breeding crashes google chrome.

After breeding some pokemon, the breeding modal begins to lag after selecting a pkm, as well as the map in selecting a rout. 
When then continuing to breed, battle ticks slow down until one tick (pkm dmg is applied) takes 3-5 seconds. 
Shortly afterwards chrome crashes. According to chrome debugging, out-of-memory error while in knockout-latest.js (if I understand it correctly) 

![Console](https://user-images.githubusercontent.com/51273302/58752881-a8a7e300-84b6-11e9-80e3-15cb7e51f9ea.PNG)

![Sources](https://user-images.githubusercontent.com/51273302/58752919-2ec42980-84b7-11e9-94a3-2a92c9319793.PNG)

Savefile: 
https://pastebin.com/wHX7ihbp

Chrome Version: Version 74.0.3729.169 (Official Build) (64-bit)
last sync with github: 01.06.2019 1pm (ish)

**Comment by RedSparr0w** [comment]
Have experienced this also _(excluding the crashing)_, browser just slows down to a crawl, but only happens on my laptop with minimal available memory.
Refresh fixes it.
Maybe a memory leak in the breeding, probably a good idea to track memory usage while breeding and not doing anything else.

**Comment by Aegyo** [comment]
How much breeding does it take to cause this issue? I have been trying for about 15 minutes without noticing any lag.

Are we sure this is caused by breeding? We should probably test leaving the game on a route, and leaving the game in town for a while to see if it could be something else.

**Comment by Quindon** [comment]
Sorry, didn't notice the question. 
How long does it take: about an hour /one and a half

Not quite sure its accually caused by breeding anymore tho. 
I have the rewrite idling overnight for shards and it is stable, but had a few (2-3) crashes while exploring gen2 without breeding. 
Might be caused by switching routes ( which also happens to be what you do when breeding alot).

**Comment by RedSparr0w** [comment]
Looks like it is actually from changing routes:
```javascript
setInterval(()=>{
	MapHelper.moveToRoute(Math.floor(Math.random() * 6), 0);
}, 10);
```
watch the memory usage climb

**Comment by Ishadijcks** [comment]
Interesting, any idea what might cause it?

**Comment by jameswasson** [comment]
After commenting some code out for moveToRoute, it seems the problem may lie in the addClass and/or removeClass calls.
This was done on a save file that could access routes 1-25 running RedSparr0w's above script.
![Code](https://user-images.githubusercontent.com/7018593/59143677-2cb00e00-8982-11e9-8a55-d3e0bc09b775.PNG)
![Graph](https://user-images.githubusercontent.com/7018593/59143678-2cb00e00-8982-11e9-8798-eccd52a64b21.PNG)

**Comment by RedSparr0w** [comment]
It looks like the `$("[data-route.....addClass(...` isn't actually needed, It's all calculated in `calculateRouteCssClass`, but even with those lines removed, the memory usage still sky rockets.
