### ISSUE TITLE
Number of Pokeballs not reset when revisiting safari zone

### ISSUE THREAD

**Issue by jameswasson** [Ishadijcks/pokeclicker#343]
When the safari zone loads (statically, with the web page) the value ```Safari.balls``` is set to 30. This number is never reset to 30 until the page is refreshed.

This allows for the player to lose all of their pokeballs and revisit the safari zone with 0 pokeballs. They can then continue to use pokeballs as ```Safari.balls``` reaches negative values.

There are two possible expected behaviors for entering the safari zone. It's up for discussion regarding which one we should use:
1. Whenever the player enters the safari zone they enter with 30 pokeballs.
2. The player starts with 30 pokeballs. Whenever the player enters the safari zone, they enter with the number of pokeballs they currently have (ex: a player enters, throws 5, leaves, and re-enters with 25 left). If the player enters the safari zone with 0 pokeballs, the number is reset to 30.

**Comment by Ishadijcks** [comment]
Number 1 sounds more reasonable, especially when you consider that the player will be able to buy more at the start of a run.
