### ISSUE TITLE
Pokedex ends at Nr.244 instead of 251

### ISSUE THREAD

**Issue by Quindon** [Ishadijcks/pokeclicker#356]
Pokedex only shows Pokemon up to Nr.244,Nr.245-251 are missing

![image](https://user-images.githubusercontent.com/51273302/59161103-87f71300-8ade-11e9-80f6-da8042df53f1.png)

**Comment by Aegyo** [comment]
Have you encountered any pokemon past 244

**Comment by Quindon** [comment]
Yes, the pokemonlist on the left is sorted by Dex-nr. so the last 7 are all 245+

**Comment by RedSparr0w** [comment]
Nice spotting!

I can also confirm this issue.

**Comment by RedSparr0w** [comment]
It seems that non of Pokemon defeated in dungeons increase `player.defeatedAmount`,
You can easily test this by completing Digletts cave and checking `player.defeatedAmount[50]()`.
