### ISSUE TITLE
Text on the map is selectable

### ISSUE THREAD

**Issue by dennism1997** [Ishadijcks/pokeclicker#36]
![image](https://user-images.githubusercontent.com/8763360/27770606-eaad5a2e-5f41-11e7-864f-90ee99fde521.png)
As shown, the text on the map is selectabel. Might also be a good idea to apply mouse::hover on them

**Comment by Ishadijcks** [comment]
I remember writing a `.no-select` css class a while ago, I'll see if I can find it.
Most of the game shouldn't be selectable as it looks ugly and can happen when clicking a lot.

What would you need the mouse:hover for?

**Comment by dennism1997** [comment]
I mean that you get the pointer hand when hovering over them, indicating that it is clickable

**Comment by Ishadijcks** [comment]
Ah I see, agreed

**Comment by Ishadijcks** [comment]
Fixed it.
Notice the towns do not have a mouse yet, as I still have to rewrite the svg for them.

**Comment by dennism1997** [comment]
Fixed that in one of my commits
