### ISSUE TITLE
Amount of route kills shown continues growing past 10

### ISSUE THREAD

**Issue by Aegyo** [Ishadijcks/pokeclicker#39]
## Expected Behavior

After 10 route kills, the info at the top should say 10/10

## Current Behavior

The info says the exact route kills /10

## Possible Solution

setting the data-bind to `text: Math.min(10, Player.routeKillsObservable())` will work, however it will continue to check every time you defeat a pokemon, so I think there is a better solution than this.

**Comment by Ishadijcks** [comment]
I already fixed this on the map branch. I put the Math.min in the observable calculator.

**Comment by Aegyo** [comment]
Ah ok, didn't realise
