### ISSUE TITLE
Should a new Pokémon be generated every time the player goes to a new route?

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/pokeclicker#41]
It makes farming for shinies/final Pokémon much easier.
- One option could be to only let the player move when the enemy is below x% health.

- Or we could queue the moving action for when the net Pokémon is defeated/captured, but this might make moving around the map kind of clunky.

- What we also could do is store the route that a Pokémon is spawned on in the battlePokémon, and let the player move around freely, without spawning a new Pokémon. When the enemy is defeated the kill counts towards the old route, and a pokemon with stats from the current route is spawned.

Let me know what you think!

**Comment by dennism1997** [comment]
I think it's kinda weird if you can start a battle in one route and finish it in another. The last idea could work but still is a bit odd. I think the easiest and best solution is to be able to move any time and just spawn a new pokemon everytime you move. The first idea is very irritating if you missclick

**Comment by Ishadijcks** [comment]
We decided to not change this mechanic.
