### ISSUE TITLE
Create Key items

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/pokeclicker#50]
The player needs to acquire the key item to unlock a feature.
In `GameConsts` add an enumerator `KeyItem` with all names of the key items.
Each feature we create will have a `KeyItemRequirement` of type `GameConsts.KeyItem`, and a method `hasAccess()` the checks if the player has the KeyItem

@Aegyo you created something like this that I haven't fully looked at, can it be easily ported?

In the menu drawer, the Key item button should display a bag looking interface that gives information about each key item. I'll create the interface.

List of key items:

Name | Feature | Where to get it | Item
------------ | ------------- | ------------- | -------------
Shard case | Shards | First prestige | http://www.serebii.net/itemdex/sprites/lenscase.png
Dungeon pass | Dungeons | Found on route 1 | 
Underground key | Underground | Bought for 10 quest points | http://www.serebii.net/itemdex/sprites/basementkey.png
Safari ticket | Safari Zone | Fuchsia City gym defeat | http://www.serebii.net/itemdex/list/keyitem.shtml
Hatchery | Breeding | Pewter city gym defeat | 
 _Name needed_ | Mom | First level 100 Pokémon | Moms letter
Teachy TV | Oak explain | At the start | http://www.serebii.net/itemdex/sprites/teachytv.png
_Name needed_ | Garden | First seed drop | http://www.serebii.net/itemdex/sprites/wailmerpail.png

**Comment by Aegyo** [comment]
There isn't really anything worth porting from that old pr I made, most of it was getting oak to explain things at the correct time, and hiding features until they had been explained. Knockout is much better for that.
