### ISSUE TITLE
Port the underground system from the previous version

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/pokeclicker#52]
- [x] Port most of the code from the old version.
- [x] Create a class for UndergroundItem.
- [x] Create a class for Underground.
- [x] Make sure fossils can be bred.
- [x] Add daily deals.
- [ ] Perhaps create rewards that tie in with the main game (ancient berries or something)

**Comment by Aegyo** [comment]
Where should the underground be accessed from? Right now I've just added a button in the start menu which opens a modal like in the old version.

**Comment by dennism1997** [comment]
We thought about putting it in a certain location where you can reach the underground. For example, instead of southern diglett cave. Then you can go to that location and go into the underground from there.
