### ISSUE TITLE
Design the Pokéball selection interface

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/pokeclicker#60]
Currently it looks like this:
![image](https://user-images.githubusercontent.com/9715314/28013249-b2739c86-6568-11e7-93b9-6365b3ddfcea.png)

The idea is that the player can select which Pokéball to use for new and Caught Pokémon.

It's really confusing to use with the numbers in the bottom, so I'm looking for something better.

Thoughts?

**Comment by Aegyo** [comment]
How about something like this?
![Pokeball Selection](https://puu.sh/wJKkF/f1da8287a8.png)

**Comment by Ishadijcks** [comment]
Ah yeah, although I would remove the infinity
