### ISSUE TITLE
Create a JSON object to save the player variables

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/pokeclicker#7]
Since `Player` is now a static class, we can't simply convert it to JSON and save it in the localstorage.
A seperate `save` and `load` function need to be written in a `SaveFileHelper` class to create a plain js object that can be converted like described.

**Comment by dennism1997** [comment]
https://github.com/JohnWeisz/TypedJSON

**Comment by Ishadijcks** [comment]
Fixed
