### ISSUE TITLE
Towns should have color indicators

### ISSUE THREAD

**Issue by dennism1997** [Ishadijcks/pokeclicker#79]
Towns should have color indicators, for when they are unlocked and you are in them

## Current Behavior
All towns have the same color

## Improved Behavior
- When you are able to move into a town, it becomes another color (eg. orange)
- When you are in a town, the color becomes another color (eg. green).

## Reason for change
Improves clarity

## Possible Solution
make a calculatecssclass method in the maphelper

**Comment by BaineGames** [comment]
pull request for TownHighlights should resolve this issue @dennism1997
