### ISSUE TITLE
Add tooltips to instruct new players

### ISSUE THREAD

**Issue by dennism1997** [Ishadijcks/pokeclicker#80]
I think we should use some tooltip library that can instruct new players and help them at their start.
Maybe something like [tippy.js](https://atomiks.github.io/tippyjs/) or [opentip](http://www.opentip.org/)?
What do you think?

**Comment by Ishadijcks** [comment]
What is wrong with bootstrap tooltips? Now that we know how they work with knockout.

**Comment by dennism1997** [comment]
It requires a lot of code for simple things, like showing a tooltip programmatically and making it dissapear when the binded element gets clicked on once. Especially Opentip looks really easy to use

**Comment by Ishadijcks** [comment]
Alright, does it work with knockout correctly?

**Comment by dennism1997** [comment]
Not 100% sure, but you can insert html in the content and escape it. So I can't tell why it would not work

**Comment by Ishadijcks** [comment]
Opentip looks good
