### ISSUE TITLE
Balancing for a playable game

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/pokeclicker#83]
Final things we need to balance before the beta

- [x] Main battling system with type effectiveness
- [x] Key items unlocking the game
- [ ] Money gain from battling
- [ ] Exp gain from battling
- [ ] Dungeon token gain and dungeon cost
- [ ] Oak item xp gain and bonuses
- [ ] Breeding time
- [ ] Gym health and xp gain
- [ ] Fill in the shops and item prices
- [ ] Balance Pokéball gain

**Comment by xpvolcanionYT** [comment]
Nerf the money obtained from battling. It's too low. I'd say maybe buff it up 10% more.

**Comment by xrago** [comment]
no thats a to low maybe 20%

**Comment by Ishadijcks** [comment]
Not a very specific or helpful issue.
