### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/pokeclicker#99]
So as with every game, this game needs achievements.
Achievements are awesome.
I want to implement around 500 of them, because that's cool.
I haven't found a way to do it efficiently yet, but I want each achievement to give a bonus to money/exp gain. Having all achievements will give you a +100% bonus.

Below we can compile a list of all possible achievements.
It is possible for some stats to appear multiple times.

- [x] Gain money 100/1,000/10,000/100,000/1,000,000/10,000,000
- [x] Gain tokens 100/1,000/10,000/100,000/1,000,000
- [x] Gain quest points 100/1,000/10,000/100,000
- [x] Gain diamonds 100/1,000/10,000
- [x] Capture Unique Pokémon 1/10/20/30/40/50/75/100/151
- [x] Capture Shiny Pokémon 1/10/20/30/40/50/75/100/151

- [x] Defeat Pokémon 100/1,000/10,000/100,000/1,000,000 times.
- [x] Capture Pokémon 100/1,000/10,000/100,000/1,000,000 times.

- [x] Click 10/100/1,000 times.
- [x] Find items 1/10/100/1,000/10,000 times.
- [x] Have Pokemon Attack: 100/1,000/5,000/10,000/25,000
- [x] Dig items 1/10/100/1,000/10,000 times.
- [x] Dig deeper 1/10/100/1,000 times.

For each Pokeball
- [x] Get Pokeballs 1/10/100/1,000/10,000/100,000

Each gym and E4:
- [x]     Defeat 1/10/100/1,000 times.

Each dungeon:
- [x]     Clear 1/10/100/1,000 times.

Each route:
- [x]     Defeat 100/1,000/10,000 Pokemons.

- [x] Hatch eggs 1/10/100/1,000/10,000 times.

**Comment by Nyargleblargle** [comment]
get 100 pokeballs seems to check if 10 pokeballs have been collected.

**Comment by Ishadijcks** [comment]
I just fixed it :)

**Comment by Aegyo** [comment]
This is waiting on #160 and #134 for the last two achievement types. Also the actual giving bonus to money and xp gain isn't done, but calculating that bonus % is.
